version: '3'

services:
  couchdb1:
    image: healthcatalyst/fabric.docker.couchdb
    volumes:
      - db-data:/opt/couchdb/data
    environment:
      - NODENAME=couchdb1
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    ports:
      - "5984:5984"
    networks:
      - dbnet
  
  setup:
    image: healthcatalyst/fabric.docker.couchdb
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    command: bash -c "/opt/couchdb/wait-for-it.sh couchdb1:5984 -t 300 -- ./configure-single-node.sh"
    depends_on:
      - couchdb1
    networks:
      - dbnet

networks:
  dbnet:

volumes:
  db-data:
